services:
  telegram-downloader:
    image: ghcr.io/darkomg/telegram-downloader:latest
    build: .
    container_name: telegram-downloader
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_ID=your_api_id_here
      - API_HASH=your_api_hash_here
      - DATA_DIR=/data
      - DOWNLOADS_DIR=/downloads
    volumes:
      - ./data:/data
      - /DATA/.media/SSD1TERA:/downloads
